apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: ecommerce-mf
data:
  PORT: "3000"
  HOST: "0.0.0.0"
  DATABASE_URL: "postgresql://app_user:app_password@postgres:5432/ecommerce"
  # ELB host updated for browser CORS origin
  CORS_ORIGIN: "http://a5d10a03df4854b31852097b4df725ec-1461367908.us-east-1.elb.amazonaws.com"
  SESSION_TTL_HOURS: "24"
