apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: ecommerce-mf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          # Account ID updated for ECR image path
          image: 385576631527.dkr.ecr.us-east-1.amazonaws.com/ecommerce-mf/cart:latest
          ports:
            - containerPort: 80
