apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: ecommerce-mf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
        - name: shell
          # Replace YOUR_ACCOUNT_ID with your 12-digit AWS account ID
          image: YOUR_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/ecommerce-mf/shell:latest
          ports:
            - containerPort: 80
